Updating genpolicy to accomdate CRI request format
SethHollandsworth/kata-containers pull request #1
Opened 2024-08-07 16:22 UTC by ksayid

### Environment Variables Update
Previous format:
```json
"Env": [
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
]
```
New format:
```json
"envs": [
  {
    "key": "PATH",
    "value": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  }
]
```
### Removed Features:
* Removed dmverity hashing
* Removed references to pause container

2024-08-07 16:49 UTC, SethHollandsworth requested changes
just a couple things to look at, thanks!

2024-08-07 16:49 UTC, SethHollandsworth commented on src/tools/genpolicy/src/containerd.rs
>          Env: Vec::new(),
let's comment out `Env` in the output/wherever it's no longer needed

2024-08-07 16:49 UTC, SethHollandsworth commented on src/tools/genpolicy/src/registry.rs
> +// async fn get_verity_hash(
if these functions aren't referenced anywhere, I think it's fine to leave them uncommented. Unless they're throwing compilation errors

2024-08-07 16:49 UTC, SethHollandsworth commented on src/tools/genpolicy/src/verity.rs
> +// // use generic_array::{typenum::Unsigned, GenericArray};
same thing as above with unreferenced code

2024-08-07 17:08 UTC, ksayid commented on src/tools/genpolicy/src/registry.rs
> +// async fn get_verity_hash(
yeah they throw compilation errors, but I think there's a flag for ignoring these type of errors

2024-08-07 17:13 UTC, SethHollandsworth commented on src/tools/genpolicy/src/registry.rs
> +// async fn get_verity_hash(
ahh leave them commented then, we'll delete once we're sure they're not in use

2024-08-08 14:08 UTC, ksayid commented on src/tools/genpolicy/src/containerd.rs
>          Env: Vec::new(),
done!

2024-08-08 14:14 UTC, SethHollandsworth approved these changes
lgtm, we'll clean up later once we have a PoC

2024-08-08 14:18 UTC, merged